// <auto-generated />
using System;
using Bayolu.AppService.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bayolu.AppService.Migrations
{
    [DbContext(typeof(BayolyDbContext))]
    [Migration("20200831082935_MakeUserAndReviewrOne2One")]
    partial class MakeUserAndReviewrOne2One
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bayolu.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)")
                        .HasMaxLength(1500);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("OriginalFolder")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<decimal>("StorageCapacity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<Guid?>("UserReviews")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserReviews");

                    b.ToTable("User","Bayolu");
                });

            modelBuilder.Entity("Bayolu.Domain.User", b =>
                {
                    b.HasOne("Bayolu.Domain.User", "UserReviewsBy")
                        .WithMany()
                        .HasForeignKey("UserReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
